import { TagMap, TagTasksMap, TaskMap } from "../Converters/V2_types";

export const getStatisticsV2 = (tagMap: TagMap, tagTaskMap: TagTasksMap, taskMap: TaskMap) => {
    // topicStats = [
    //     {
    //     topicId= ...
    //     totalTasks= ...
    //     completedTasks= ...
    //     plannedTasks= ...
    //     totalRecursiveTasks =...
    //     completedRecursiveTasks = ...
    //     plannedRecursiveTasks = ...
    // }
    // 
    // ]

}
